#!/bin/bash
#########################################################
# Configure Ubuntu in Dual Boot
#########################################################
# Ch3i- 02/19/2015
#########################################################

#########################################################
# Functions
#########################################################

FUNC_END(){
echo -e "\033[45m##########################################################################
#                          Updates Finished                              #
##########################################################################"
cat <<"EOT"
                                                                          
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!`   `4!!!!!!!!!!~4!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!   <~:   ~!!!~   ..  4!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ~~~~~~~     ud$$$$$  !!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ~~~~~~~~~: ?$$$$$$$$$  !!!!!!!!!!!!!!
!!!!!!!!!!!`     ``~!!!!!!!!!!!!!!  ~~~~~           *$$$$$k `!!!!!!!!!!!!!
!!!!!!!!!!  $$$$$bu.   ~!~`     .   ~~~~      :~~~~          `4!!!!!!!!!!!
!!!!!!!!!  $$$$$$$$$$$c  .zW$$$$$E ~~~~      ~~~~~~~~  ~~~~~:   !!!!!!!!!!
!!!!!!!!! d$$$$$$$$$$$$$$$$$$$$$$E ~~~~~     ~~~~~~~~    ~~~~~  !!!!!!!!!!
!!!!!!!!> 9$$$$$$$$$$$$$$$$$$$$$$$  ~~~~~~~  ~~~~~~~~     ~~~~  !!!!!!!!!!
!!!!!!!!> $$$$$$$$$$$$$$$$$$$$$$$$b   ~~~     ~~~~~~~      ~~~  !!!!!!!!!!
!!!!!!!!> $$$$$$$$$$$$$$$$$$$$$$$$$$$cuuue$$N.   ~        ~~~  !!!!!!!!!!!
!!!!!!!!! **$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$Ne  ~~~~~~~~  `!!!!!!!!!!!
!!!!!!!!!  J$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$N  ~~~~~  zL  !!!!!!!!!!
!!!!!!!!  d$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$c     z$$$c `!!!!!!!!!
!!!!!!!> <$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$> 4!!!!!!!!
!!!!!!!  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  !!!!!!!!
!!!!!!! <$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$*    ....:!!
!!!!!!~ 9$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$e@$N  !!!!!!!
!!!!!!  9$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  !!!!!!!
!!!!!!  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  $$$$$$$$$$$~ ~~4!!!!
!!!!!!  9$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$    $$$$$$$Lue  :::!!!!
!!!!!!> 9$$$$$$$$$$$$   $$$$$$$$$$$$$$$$$$$$$$$$$$$    $$$$$$$$$$  !!!!!!!
!!!!!!!  $$*$$$$$$$$E    $$$$$$$$$$$$$$$$$$$$$$$$$$$u.@$$$$$$$$$E  !!!!!!!
!!!!~`   .eeW$$$$$$$$   :$$$$$$$$$$$$$***$$$$$$$$$$$$$$$$$$$$u.    `~!!!!!
!!> .:!h  $$$$$$$$$$$$ed$$$$$$$$$$$$Fz$$b $$$$$$$$$$$$$$$$$$$$$F  !h.  !!!
!!!!!!!!L  $**$$$$$$$$$$$$$$$$$$$$$$ *$$$ $$$$$$$$$$$$$$$$$$$$F  !!!!!!!!!
!!!!!!!!!   d$$$$$$$$$$$$$$$$$$$$$$$$buud$$$$$$$$$$$$$$$$$$$$   !!!!!!!!!!
!!!!!!! .<!  #$$* $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$*  :!!!!!!!!!!!
!!!!!!!!!!!!:   d$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#  :!!!!!!!!!!!!!
!!!!!!!!!!!~  :   #$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$*     !!!!!!!!!!!!!!!
!!!!!!!!!!  !!!!!:   ^ **$$$$$$$$$$$$$$$$$$$$**#      .:<!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!:...                      .::!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                                                                          
EOT
echo -e "\033[0m\n\n"
}

FUNC_TOP(){
echo -e "\033[42m#########################################################
#         Custom My Master - New master deploy          #
#########################################################\033[0m\n\n"

if [ "$STATUS_UPDATE_UPDATE" == "1" ]
then
	echo -n "Update in progress...";
fi
if [ "$STATUS_UPDATE_UPDATE" == "2" ]
then
	echo "Update in progress... Done";
fi

if [ "$STATUS_UPDATE_GRUB" == "1" ]
then
	echo -n "Grub configuration in progress...";
fi
if [ "$STATUS_UPDATE_GRUB" == "2" ]
then
	echo "Grub configuration in progress... Done";
fi

if [ "$STATUS_UPDATE_GNOME" == "1" ]
then
	echo -n "Gnome configuration in progress...";
fi
if [ "$STATUS_UPDATE_GNOME" == "2" ]
then
	echo "Gnome configuration in progress... Done";
fi

if [ "$STATUS_UPDATE_FOG" == "1" ]
then
	echo -n "Fog Service configuration in progress...";
fi
if [ "$STATUS_UPDATE_FOG" == "2" ]
then
	echo "Fog Service configuration in progress... Done";
fi
}

#########################################################
# Vars initialization
#########################################################
STATUS_UPDATE_UPDATE=0
STATUS_UPDATE_GRUB=0
STATUS_UPDATE_GNOME=0
STATUS_UPDATE_FOG=0

#########################################################
# Menu
#########################################################
clear

FUNC_TOP

echo -e "\033[42m1 - Host Update (apt-get update/upgrade) 
2 - Grub Configuration                   
3 - Gnome Authentication                 
4 - Enable Fog Service                   
5 - All                                  
6 - Exit                                 \033[0m\n"
echo -n "Your select : " 
read -e HOST_ACTIONS


#########################################################
# Host Update
#########################################################
if [ "$HOST_ACTIONS" == "1" ] || [ "$HOST_ACTIONS" == "5" ]
then
	clear
	STATUS_UPDATE_UPDATE=1
	FUNC_TOP
	
	apt-get update > /dev/null 2>&1
	apt-get -y upgrade  > /dev/null 2>&1
	
	clear
	STATUS_UPDATE_UPDATE=2
	FUNC_TOP
fi


#########################################################
# Grub Configuration (Set default boot, timeout, ...)
#########################################################
if [ "$HOST_ACTIONS" == "2" ] || [ "$HOST_ACTIONS" == "5" ]
then
	#########################################################
	# Update Grub Configuration (Grub 2.0+)
	#########################################################
	
	clear
	STATUS_UPDATE_GRUB=1
	FUNC_TOP

	# Enabled grub-set-default
	sed -i -e "s/\GRUB_DEFAULT=0/\GRUB_DEFAULT=saved/g" /etc/default/grub

	# Set timeout at 30 seconds
	sed -i -e "s/\GRUB_TIMEOUT=10/\GRUB_TIMEOUT=10/g" /etc/default/grub

	# Removed memtest from /boot
	rm /boot/memtest*  > /dev/null 2>&1

	# Update Entry
	update-grub2  > /dev/null 2>&1

	# Set default entry from Eric Zhiqiang Ma (http://www.ericzma.com)
	grep "^menuentry" /boot/grub/grub.cfg | cut -d "'" -f2 >/tmp/grub2-select.entries

	items=`cat /tmp/grub2-select.entries`

	linen=`cat /tmp/grub2-select.entries | wc -l`
	
	echo "\n"
	
	j=0
	while [ $j -lt $linen ]
	do
		let "j=j+1"
		echo -n "$j  "
		echo "$items" | head -n $j | tail -n1
	done

	echo -n -e "\nYour select: "
	read sel

	selected=`echo "$items" | head -n $sel | tail -n1`

	grub-set-default "$selected"
	grub-mkconfig -o /boot/grub/grub.cfg  > /dev/null 2>&1
	
	clear
	STATUS_UPDATE_GRUB=2
	FUNC_TOP
fi



#########################################################
# Gnome Authentication (Disable login history)
#########################################################
if [ "$HOST_ACTIONS" == "3" ] || [ "$HOST_ACTIONS" == "5" ]
then
	#########################################################
	# Update Gnome Authentication
	#########################################################
	
	clear
	STATUS_UPDATE_GNOME=1
	FUNC_TOP
	
	echo "greeter-hide-users=true
greeter-show-manual-login=true" >> /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf

	clear
	STATUS_UPDATE_GNOME=2
	FUNC_TOP
	
	fi

#########################################################
# Enable Fog Service
#########################################################
if [ "$HOST_ACTIONS" == "3" ] || [ "$HOST_ACTIONS" == "5" ]
then
	
	clear
	STATUS_UPDATE_FOG=1
	FUNC_TOP
	
	#########################################################
	# Install/update mysql-client
	#########################################################
	apt-get -y install mysql-client  > /dev/null 2>&1

	#########################################################
	# Copy/update rename_host_fog script in init.d
	#########################################################
	if [ -f /etc/init.d/rename_host_fog ]
	then
		rm /etc/init.d/rename_host_fog
	fi
	cp rename_host_fog /etc/init.d/rename_host_fog

	#########################################################
	# Update rename_host_fog rights
	#########################################################
	chmod 755 /etc/init.d/rename_host_fog

	#########################################################
	# Enable rename_host_fog service at startup
	#########################################################
	/usr/lib/insserv/insserv rename_host_fog
	
	clear
	STATUS_UPDATE_FOG=2
	FUNC_TOP
	
fi

#########################################################
# Restart host
#########################################################
if [ "$HOST_ACTIONS" == "1" ] || [ "$HOST_ACTIONS" == "2" ] || [ "$HOST_ACTIONS" == "3" ] || [ "$HOST_ACTIONS" == "4" ] || [ "$HOST_ACTIONS" == "5" ]
then
	
	clear
	FUNC_TOP
	
	echo -e "\n\n"
	echo -e -n "\033[41mRestart host ? (y/N) : \033[0m"; read -e HOST_RESTART
	
	clear
	FUNC_END
	
	if [ "$HOST_RESTART" == "y" ] || [ "$HOST_RESTART" == "Y" ]
	then
		sleep 3
		grub-reboot 0
		/sbin/init 6
	fi
else
	clear
	exit
fi